### ISSUE TITLE
Documentación sección técnicas y herramientas 

### ISSUE THREAD

**Issue by fma0043** [fma0043/GESPRO_Practicas#10]
Indicaremos una visión general de la herramienta, descripción funcional breve, utilización de la herramienta en el proyecto y referenciar a Web o libro.

**Comment by fma0043** [comment]
La documentación de sección técnicas esta correcta, pero te aconsejo revisar y mejorar la de herramientas, creo que es mejorable @moi0006

**Comment by moi0006** [comment]
Ya lo he completado! @fma0043

**Comment by fma0043** [comment]
Perfecto¡¡¡ @moi0006
