### ISSUE TITLE
Cargar un proyecto PHP - Java - C# - JavaScript

### ISSUE THREAD

**Issue by fma0043** [fma0043/GESPRO_Practicas#13]
Cargaremos distintos proyectos con medidas de pruebas y cobertura

**Comment by moi0006** [comment]
Parece que en el de PHP tienes algún bug

**Comment by fma0043** [comment]
Gracias, lo reviso @moi0006

**Comment by moi0006** [comment]
@fma0043 Perfecto! Sin fallos!
