### ISSUE TITLE
Elaboración de la documentación sobre el proyecto

### ISSUE THREAD

**Issue by fma0043** [fma0043/GESPRO_Practicas#2]
Elaboración de los apartados 1. Introducción y 2. Objetivos de la memoria del proyecto utilizando LaTeX y la plantilla proporcionada para el TFG.

**Comment by fma0043** [comment]
¡¡¡¡¡Gran trabajo!!!!!!! todo un acierto @moi0006

**Comment by moi0006** [comment]
@fma0043 Gracias :)
