### ISSUE TITLE
Calcular información estadística y configurar quality gate para SonarQube 

### ISSUE THREAD

**Issue by fma0043** [fma0043/GESPRO_Practicas#23]
Calcular la información estadística correspondiente a los percentiles 1 y 3 de un conjunto de métricas obtenidas con SonarQube y configurar un Quality Gate con los valores obtenidos.

**Comment by moi0006** [comment]
@fma0043 el quality gate está flojo, revisalo!

**Comment by fma0043** [comment]
revisado¡ @moi0006
