### ISSUE TITLE
Aprendizaje del entorno Bitbucket 

### ISSUE THREAD

**Issue by moi0006** [fma0043/GESPRO_Practicas#5]
Necesidad de aprender las funcionalidades que ofrece Bitbucket para la gestión de un repositorio.

Se pretende realizar una gestión de las tareas llevadas a cabo durante la realización del proyecto mediante incidencias (issues), componentes (components) e hitos (milestones).

**Comment by moi0006** [comment]
¿Ha sido muy dificil aprenderlo?

**Comment by fma0043** [comment]
En principio pensaba que iba a ser mas fácil, pero una vez trabajado con ello es sencillo @moi0006
