### ISSUE TITLE
Despliegue de instancia remota de sonarqube

### ISSUE THREAD

**Issue by fma0043** [fma0043/GESPRO_Practicas#7]
Despliegue de una instancia remota de la herramienta SonarQube en la plataforma de OpenShift. Para el despliegue se utilizarán las herramientas de cliente que proporciona OpenShift.

**Comment by fma0043** [comment]
He visto algún fallo en la configuración del servidor, te recomiendo revisarlo @moi0006

**Comment by moi0006** [comment]
@fma0043 Creo que está corregido!

**Comment by fma0043** [comment]
vale ahora si parece que todo esta bien @moi0006
